# The following represents an example of a configuration file to crawl mendeley and contentful
mendeley:
  # Target directory to store JSON
  targetDir: /tmp/mendeley-crawl

#  timeout: 10
  tokenUrl: https://api.mendeley.com/oauth/token
  trustedClientId: 4108
  trustedClientSecret:
  groupId:
  indexBuild:
    esIndexName: content
    esIndexType: literature
  gbifApiUrl: http://api.gbif-dev.org/
  controlledTags:
    "topics":
      - "Agriculture"
      - "Biodiversity_science"
      - "Biogeography"
      - "Citizen_science"
      - "Climate_change"
      - "Conservation"
      - "Data_management"
      - "Data_paper"
      - "Ecology"
      - "Ecosystem_services"
      - "Evolution"
      - "Freshwater"
      - "Human_health"
      - "Invasives"
      - "Marine"
      - "Phylogenetics"
      - "Species_distributions"
      - "Taxonomy"
    "relevance":
      - "GBIF_used"
      - "GBIF_cited"
      - "GBIF_discussed"
      - "GBIF_primary"
      - "GBIF_acknowledged"
      - "GBIF_published"
      - "GBIF_author"
      - "GBIF_mentioned"
      - "GBIF_funded"



# Optional: If included will push documents to the referenced Elastic Search index
elasticSearch:
  host: develastic-vh.gbif.org
#  port: 9300
  cluster: content-cluster

#Contentful crawler configuration
contentful:
  cdaToken: cbe898627179356da24491ea99ded861c34b78459f0362064b11d377fd6ebd97
  cmaToken: CFPAT-846cd78935cdd5faf81946c1b1f8f06ca902985e86e6ecf4f05c533b24fcadab
  spaceId: uo17ejk9rkwj
  indexBuild:
    #contentTypes: [dataUse]
    esIndexType: content
  countryVocabulary: "Vocabulary: Countries"
  newsContentType: "News"
  vocabularies:
    - "Vocabulary: Audience"
    - "Vocabulary: Countries"
    - "Vocabulary: Purpose"
    - "Vocabulary: Topic"
  contentTypes:
    - "News"
    - "Call"
    - "Data Use"
    - "Event"
    - "Ogranisation"
    - "Participant"
    - "Programme"
    - "Project"
    - "Tool"
    - "Article"
    - "Document"

#Contentful backup configuration
contentfulBackup:
  cmaToken:
  targetDir: /tmp/mendeley-crawl
