# The following represents an example of a configuration file to crawl mendeley and contentful
mendeley:
  # Target directory to store JSON
  targetDir: /tmp/mendeley-crawl

#  timeout: 10
  tokenUrl: https://api.mendeley.com/oauth/token
  trustedClientId: 4108
  trustedClientSecret:
  groupId:
  indexBuild:
    esIndexName: content
    esIndexType: literature

# Optional: If included will push documents to the referenced Elastic Search index
elasticSearch:
  host: develastic-vh.gbif.org
#  port: 9300
  cluster: content-cluster

#Contentful crawler configuration
contentful:
  cdaToken:
  cmaToke:
  spaceId:
  indexBuild:
    #contentTypes: [dataUse]
    esIndexName: content
    countryVocabulary: "CountryVocabulary"
    newsContentType: "News"
    vocabularies:
      - "Vocabulary1"
      - "Vocabulary2"
    contentTypes:
      - "Content 1"
      - "Content 2"

#Contentful backup configuration
contentfulBackup:
  cmaToken:
  targetDir: /tmp/mendeley-crawl
