# The following represents an example of a configuration file to crawl mendeley and contentful
mendeley:
  # Target directory to store JSON
  targetDir: "/tmp/mendeley-crawl"

#  timeout: 10
  tokenUrl: "https://api.mendeley.com/oauth/token"
  authToken: @mendeleyAuthToken
  groupId:
  indexBuild:
    esIndexName: "literature"
    esIndexAlias: "literature"
  controlledTags:
    topics:
      - "Agriculture"
      - "Biodiversity_science"
      - "Biogeography"
      - "Citizen_science"
      - "Climate_change"
      - "Conservation"
      - "Data_management"
      - "Data_paper"
      - "Ecology"
      - "Ecosystem_services"
      - "Evolution"
      - "Freshwater"
      - "Human_health"
      - "Invasives"
      - "Marine"
      - "Phylogenetics"
      - "Species_distributions"
      - "Taxonomy"
    relevance:
      - "GBIF_used"
      - "GBIF_cited"
      - "GBIF_discussed"
      - "GBIF_primary"
      - "GBIF_acknowledged"
      - "GBIF_published"
      - "GBIF_author"
      - "GBIF_mentioned"
      - "GBIF_funded"

# Optional: If included will push documents to the referenced Elastic Search index
elasticSearch:
  host: "cms-search.gbif-dev.org"
#  port: 9300
  cluster: "content-cluster"

# Optional: If included will update the GBIF registry to mark cited downloads for retention
gbifApi:
  url: "http://api.gbif-dev.org/v1/"
  username: @gbifApiUsername
  password: @gbifApiPassword

#Contentful crawler configuration
contentful:
  cdaToken: @contentfulCdaToken
  cmaToken: @contentfulCmaToken
  spaceId: @contentfulSpaceId
  environmentId: @environmentId
  indexBuild:
    #contentTypes: [dataUse]
    esIndexAlias: "content"
  countryVocabulary: "Vocabulary: Countries"
  newsContentType: "News"
  vocabularies:
    - "Vocabulary: Audience"
    - "Vocabulary: Countries"
    - "Vocabulary: Purpose"
    - "Vocabulary: Topic"
  contentTypes:
    - "News"
    - "Network"
    - "Call"
    - "Data Use"
    - "Event"
    - "Ogranisation"
    - "Participant"
    - "Programme"
    - "Project"
    - "Tool"
    - "Article"
    - "Document"
    - "Help"
    - "Notification"

#Contentful backup configuration
contentfulBackup:
  cmaToken:
  targetDir: "/tmp/mendeley-crawl"
